---
name: rule1
description: "Rule which sends an email when an email from test.nihilent.5375@gmail.com is received"
pack: stackstrom_azure
enabled: true
trigger:
  type: stackstrom_azure.imap.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: create vm
    type: contains
action:
  ref: stackstrom_azure.vm_action
  parameters:
    Group_Name: '{{trigger.group}}'
    Location: '{{trigger.location}}'
    VM_Name: '{{trigger.vmname}}'